name: battle_net
description: Dart wrapper client for Battle.Net API https://develop.battle.net/documentation
version: 0.1.1
repository: https://github.com/vmpay/battle_net_dart
issue_tracker: https://github.com/vmpay/battle_net_dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.5
  meta: ^1.8.0
  collection: ^1.16.0

dev_dependencies:
  test: ^1.22.2