name: battle_net
description: Battle Net API wrapper
version: 0.0.1
repository: https://github.com/vmpay/battle_net_dart
issue_tracker: https://github.com/vmpay/battle_net_dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.5

dev_dependencies:
  test: ^1.22.2