# This is a basic workflow to help you get started with Actions

name: Quality check

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Reusable workflow call
  workflow_call:
    secrets:
      CLIENT_ID:
        required: true
      CLIENT_SECRET:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      # Verify the use of 'dart format' on each commit
      - name: Verify formatting
        run: dart format -o none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis
      - name: Analyze project source
        run: dart analyze --fatal-infos

      # Ensure your shell script is executable
      - name: Make shell script write_credentials.sh executable
        run: chmod +x .github/workflows/write_credentials.sh

      # Run bash script in order to provide test credentials
      - name: Write down test credentials
        run:  ./.github/workflows/write_credentials.sh
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - name: Install dependencies tests with coverage
        run: dart pub global activate coverage

      - name: Run tests with coverage
        run: dart pub global run coverage:test_with_coverage

      - name: Install LCOV
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Generate coverage report
        run: genhtml coverage/lcov.info --output-directory coverage/html

      - name: Check coverage percentage
        id: check_coverage
        run: |
          LINES_FOUND=$(grep -E '^LF:' coverage/lcov.info | awk -F':' '{s+=$2} END {print s}')
          LINES_HIT=$(grep -E '^LH:' coverage/lcov.info | awk -F':' '{s+=$2} END {print s}')
          if [ -z "$LINES_FOUND" ] || [ "$LINES_FOUND" -eq 0 ]; then
            COVERAGE_PERCENTAGE=0.0
          else
            COVERAGE_PERCENTAGE=$(echo "scale=2; ($LINES_HIT / $LINES_FOUND) * 100" | bc -l)
          fi
          echo "Overall coverage: $COVERAGE_PERCENTAGE%"
          if (( $(echo "$COVERAGE_PERCENTAGE < 90.0" | bc -l) )); then
            echo "Code coverage is below 90%! Failing pipeline."
            exit 1
          fi

      # The pub.dev site uses the analysis tool pana to calculate pub points.
      # This is run automatically on the pub.dev site whenever you publish a new package,
      # or a new version of an existing package.
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Calculating pub points prior to publishing
        run: |
          dart pub global activate pana
          dart pub global run pana --exit-code-threshold 0 --json